#공통
spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp
  jpa:
    database: MYSQL
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB
  ssl:
    enabled: true
    key-alias: testkeystore
    key-store: testkeystore.pkcs12
    key-store-password: '@test123@'
    key-password: '@test123@'
    trust-store: testtrust.pkcs12
    trust-store-password: '@test123@'     
   
 
server:
  port: 8080
  tomcat:
    max-http-post-size: 5MB
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#security
security:
  invalidate-session: false

img:
  path: /img  
js:
  path: /js
css:
  path: /css
asset:
  path: /asset
